# Format: RequestClassName=ResponseClassName:requestField1=responseField1,requestField2=responseField2
CreateUserRequest=CreateUserResponse:username=username,role=role
DepositRequest=DepositResponse:id=id,balance=balance
TransferMoneyRequest=TransferMoneyResponse:senderAccountId=senderAccountId,receiverAccountId=receiverAccountId,amount=amount