# Format: RequestClassName=ResponseClassName:requestField1=responseField1,requestField2=responseField2
CreateUserRequest=CreateUserResponse:username=username,role=role
DepositRequest=DepositResponse:id=id,balance=balance
TransferMoneyRequest=TransferMoneyResponse:senderAccountId=senderAccountId,receiverAccountId=receiverAccountId,amount=amount
PutCustomerProfileResponse=PutCustomerProfileResponse:message=message,customer=customer
GetCustomerProfileResponse=GetCustomerProfileResponse:name=name
Customers=Customers:name=name,id=id,username=username,role=role